"""add purchase request domain models

Revision ID: 18bb07b63a8d
Revises: e02640199eee
Create Date: 2026-08-02 09:19:49.634186

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18bb07b63a8d"
down_revision = "e02640199eee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference_number", sa.String(length=50), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("business_justification", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "HARDWARE",
                "SOFTWARE",
                "IT_SERVICES",
                "OFFICE_SUPPLIES",
                "PROFESSIONAL_SERVICES",
                "FACILITIES",
                "TRAINING",
                "OTHER",
                name="request_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("supplier", sa.String(length=200), nullable=True),
        sa.Column("requested_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expected_purchase_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "IN_REVIEW",
                "CHANGES_REQUESTED",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="request_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("current_revision_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "currency = 'EUR'", name="ck_purchase_requests_eur_currency"
        ),
        sa.CheckConstraint(
            "current_revision_number >= 0",
            name="ck_purchase_requests_revision_non_negative",
        ),
        sa.CheckConstraint(
            "requested_amount IS NULL OR requested_amount > 0",
            name="ck_purchase_requests_positive_amount",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_requests_department_id"),
            ["department_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_requests_reference_number"),
            ["reference_number"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_requests_requester_id"),
            ["requester_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_requests_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_purchase_requests_status_created_at",
            ["status", "created_at"],
            unique=False,
        )

    op.create_table(
        "request_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_request_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column(
            "comment_type",
            sa.Enum(
                "GENERAL",
                "REQUESTER_RESPONSE",
                "APPROVER_NOTE",
                "SYSTEM_NOTE",
                name="request_comment_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(body)) > 0", name="ck_request_comments_body_not_empty"
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("request_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_comments_author_id"), ["author_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_request_comments_purchase_request_id"),
            ["purchase_request_id"],
            unique=False,
        )

    op.create_table(
        "request_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_request_id", sa.Integer(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("business_justification", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "HARDWARE",
                "SOFTWARE",
                "IT_SERVICES",
                "OFFICE_SUPPLIES",
                "PROFESSIONAL_SERVICES",
                "FACILITIES",
                "TRAINING",
                "OTHER",
                name="revision_request_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("supplier", sa.String(length=200), nullable=True),
        sa.Column(
            "requested_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expected_purchase_date", sa.Date(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("submitted_by_user_id", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "currency = 'EUR'", name="ck_request_revisions_eur_currency"
        ),
        sa.CheckConstraint(
            "requested_amount > 0", name="ck_request_revisions_positive_amount"
        ),
        sa.CheckConstraint(
            "revision_number > 0", name="ck_request_revisions_positive_revision"
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "purchase_request_id",
            "revision_number",
            name="uq_request_revisions_request_revision",
        ),
    )
    with op.batch_alter_table("request_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_revisions_department_id"),
            ["department_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_request_revisions_purchase_request_id"),
            ["purchase_request_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_request_revisions_submitted_by_user_id"),
            ["submitted_by_user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_revisions_submitted_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_request_revisions_purchase_request_id"))
        batch_op.drop_index(batch_op.f("ix_request_revisions_department_id"))

    op.drop_table("request_revisions")
    with op.batch_alter_table("request_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_comments_purchase_request_id"))
        batch_op.drop_index(batch_op.f("ix_request_comments_author_id"))

    op.drop_table("request_comments")
    with op.batch_alter_table("purchase_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_purchase_requests_status_created_at")
        batch_op.drop_index(batch_op.f("ix_purchase_requests_status"))
        batch_op.drop_index(batch_op.f("ix_purchase_requests_requester_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_requests_reference_number"))
        batch_op.drop_index(batch_op.f("ix_purchase_requests_department_id"))

    op.drop_table("purchase_requests")
    # ### end Alembic commands ###
