"""add workflow execution models

Revision ID: 653b92827181
Revises: 6e14ea68b252
Create Date: 2026-08-02 14:27:05.175829

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "653b92827181"
down_revision = "6e14ea68b252"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_cycles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_request_id", sa.Integer(), nullable=False),
        sa.Column("request_revision_id", sa.Integer(), nullable=False),
        sa.Column("workflow_configuration_id", sa.Integer(), nullable=False),
        sa.Column("cycle_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "APPROVED",
                "REJECTED",
                "CHANGES_REQUESTED",
                "SUPERSEDED",
                "CANCELLED",
                name="workflow_cycle_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cycle_number > 0", name="ck_workflow_cycles_positive_cycle_number"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"],
            ["purchase_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_revision_id"],
            ["request_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_configuration_id"],
            ["workflow_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "purchase_request_id",
            "cycle_number",
            name="uq_workflow_cycles_request_cycle",
        ),
        sa.UniqueConstraint(
            "request_revision_id", name="uq_workflow_cycles_request_revision"
        ),
    )
    with op.batch_alter_table("workflow_cycles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_cycles_purchase_request_id"),
            ["purchase_request_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_cycles_request_revision_id"),
            ["request_revision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_cycles_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_workflow_cycles_status_started_at",
            ["status", "started_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_cycles_workflow_configuration_id"),
            ["workflow_configuration_id"],
            unique=False,
        )

    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_cycle_id", sa.Integer(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "MANAGER_APPROVAL",
                "IT_REVIEW",
                "FINANCE_APPROVAL",
                "DIRECTOR_APPROVAL",
                name="execution_step_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("required_role_name", sa.String(length=100), nullable=False),
        sa.Column("assigned_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "APPROVED",
                "REJECTED",
                "CHANGES_REQUESTED",
                "SKIPPED",
                "CANCELLED",
                name="workflow_step_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason_for_inclusion", sa.Text(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_duration_hours", sa.Integer(), nullable=False),
        sa.Column(
            "sla_result",
            sa.Enum(
                "ON_TIME",
                "APPROACHING_DEADLINE",
                "OVERDUE",
                "COMPLETED_ON_TIME",
                "COMPLETED_LATE",
                name="workflow_step_sla_result",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("overdue_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "overdue_seconds IS NULL OR overdue_seconds >= 0",
            name="ck_workflow_steps_non_negative_overdue",
        ),
        sa.CheckConstraint(
            "sequence_number > 0", name="ck_workflow_steps_positive_sequence"
        ),
        sa.CheckConstraint(
            "sla_duration_hours > 0", name="ck_workflow_steps_positive_sla"
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_cycle_id"], ["workflow_cycles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_cycle_id",
            "sequence_number",
            name="uq_workflow_steps_cycle_sequence",
        ),
    )
    with op.batch_alter_table("workflow_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_steps_assigned_user_id"),
            ["assigned_user_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_workflow_steps_assignee_status",
            ["assigned_user_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_steps_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_workflow_steps_status_deadline", ["status", "deadline_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_steps_step_type"), ["step_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_steps_workflow_cycle_id"),
            ["workflow_cycle_id"],
            unique=False,
        )

    op.create_table(
        "approval_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_step_id", sa.Integer(), nullable=False),
        sa.Column("workflow_cycle_id", sa.Integer(), nullable=False),
        sa.Column("purchase_request_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVE",
                "REJECT",
                "RETURN_FOR_CHANGES",
                name="approval_decision_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            (
                "decision = 'APPROVE' "
                "OR ("
                "comment IS NOT NULL "
                "AND length(trim(comment)) > 0"
                ")"
            ),
            name="ck_approval_decisions_comment_required",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"],
            ["purchase_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_cycle_id"],
            ["workflow_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["workflow_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_step_id", name="uq_approval_decisions_workflow_step"
        ),
    )
    with op.batch_alter_table("approval_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_decisions_actor_id"), ["actor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approval_decisions_purchase_request_id"),
            ["purchase_request_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_approval_decisions_request_decided_at",
            ["purchase_request_id", "decided_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_approval_decisions_workflow_cycle_id"),
            ["workflow_cycle_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_approval_decisions_workflow_step_id"),
            ["workflow_step_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_decisions_workflow_step_id"))
        batch_op.drop_index(batch_op.f("ix_approval_decisions_workflow_cycle_id"))
        batch_op.drop_index("ix_approval_decisions_request_decided_at")
        batch_op.drop_index(batch_op.f("ix_approval_decisions_purchase_request_id"))
        batch_op.drop_index(batch_op.f("ix_approval_decisions_actor_id"))

    op.drop_table("approval_decisions")
    with op.batch_alter_table("workflow_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_steps_workflow_cycle_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_steps_step_type"))
        batch_op.drop_index("ix_workflow_steps_status_deadline")
        batch_op.drop_index(batch_op.f("ix_workflow_steps_status"))
        batch_op.drop_index("ix_workflow_steps_assignee_status")
        batch_op.drop_index(batch_op.f("ix_workflow_steps_assigned_user_id"))

    op.drop_table("workflow_steps")
    with op.batch_alter_table("workflow_cycles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_cycles_workflow_configuration_id"))
        batch_op.drop_index("ix_workflow_cycles_status_started_at")
        batch_op.drop_index(batch_op.f("ix_workflow_cycles_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_cycles_request_revision_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_cycles_purchase_request_id"))

    op.drop_table("workflow_cycles")
    # ### end Alembic commands ###
