"""add workflow configuration models

Revision ID: 6e14ea68b252
Revises: 18bb07b63a8d
Create Date: 2026-08-02 11:51:53.214485

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e14ea68b252"
down_revision = "18bb07b63a8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "low_value_threshold", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "high_value_threshold", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "it_review_threshold", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("it_review_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "high_value_threshold > 0",
            name="ck_workflow_configurations_positive_high_threshold",
        ),
        sa.CheckConstraint(
            "it_review_threshold > 0",
            name="ck_workflow_configurations_positive_it_threshold",
        ),
        sa.CheckConstraint(
            "low_value_threshold < high_value_threshold",
            name="ck_workflow_configurations_threshold_order",
        ),
        sa.CheckConstraint(
            "low_value_threshold > 0",
            name="ck_workflow_configurations_positive_low_threshold",
        ),
        sa.CheckConstraint(
            "version_number > 0", name="ck_workflow_configurations_positive_version"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_number"),
    )
    with op.batch_alter_table("workflow_configurations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_configurations_created_by_user_id"),
            ["created_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_configurations_is_active"),
            ["is_active"],
            unique=False,
        )

    op.create_table(
        "step_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_configuration_id", sa.Integer(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "MANAGER_APPROVAL",
                "IT_REVIEW",
                "FINANCE_APPROVAL",
                "DIRECTOR_APPROVAL",
                name="workflow_step_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sla_duration_hours", sa.Integer(), nullable=False),
        sa.Column("default_assignee_user_id", sa.Integer(), nullable=True),
        sa.Column("required_role_name", sa.String(length=100), nullable=False),
        sa.Column("sequence_hint", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sequence_hint > 0", name="ck_step_configurations_positive_sequence"
        ),
        sa.CheckConstraint(
            "sla_duration_hours > 0", name="ck_step_configurations_positive_sla"
        ),
        sa.ForeignKeyConstraint(
            ["default_assignee_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_configuration_id"],
            ["workflow_configurations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_configuration_id",
            "step_type",
            name="uq_step_configurations_workflow_step_type",
        ),
    )
    with op.batch_alter_table("step_configurations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_step_configurations_default_assignee_user_id"),
            ["default_assignee_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_step_configurations_workflow_configuration_id"),
            ["workflow_configuration_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("step_configurations", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_step_configurations_workflow_configuration_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_step_configurations_default_assignee_user_id")
        )

    op.drop_table("step_configurations")
    with op.batch_alter_table("workflow_configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_configurations_is_active"))
        batch_op.drop_index(batch_op.f("ix_workflow_configurations_created_by_user_id"))

    op.drop_table("workflow_configurations")
    # ### end Alembic commands ###
